name: Compilar Aplicacion

on:
  push:
    branches: [ "main" ] # Se ejecuta cuando subes cambios a la rama main
  workflow_dispatch: # Permite ejecutar el proceso manualmente desde el botón "Run workflow"

jobs:
  build:
    runs-on: windows-latest # Cambia a ubuntu-latest o macos-latest según la plataforma que necesites

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Compilar ejecutable
      run: |
        pyinstaller --onefile main.py

    - name: Guardar el ejecutable como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: Aplicacion-Compilada
        path: dist/*.exe
